name: Ci CD React v2
on: push
jobs:
    test:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          #working-directory: ./src
          
      steps:
          - name: Show local dirrectory
            run:  ls

          - name: Get repository code
            #run: echo test ci cd
            uses: actions/checkout@v4
          
          - name: npm installation
            #-name: npm install
            run: npm install
          
          - name: Test app
            #run: npm run test SKIP_PREFLIGHT_CHECK=true
            run: npm run test
    lint:
      runs-on: ubuntu-latest
      needs: test
      steps:
          - name: Get repository code
            #run: echo test ci cd
            uses: actions/checkout@v4
          
          - name: npm installation
            #-name: npm install
            run: npm install

          - name: lint installation
            run: npm install --save-dev eslint-config-react-app eslint
          
          - name: lint app
            run: ./node_modules/.bin/eslint --init
    buils:
       runs-on: ubuntu-latest
       needs: lint
       steps:
          - name: Get repository code
          #run: echo test ci cd
            uses: actions/checkout@v4
        
          - name: npm installation
            run: npm install
          
          - name: Build
            run: npm run build

          - name: Deploy..
            run: echo Deploy