name: Ci CD React v2
on: push
jobs:
    testjob:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          #working-directory: ./src
          
      steps:
          - name: Show local dirrectory
            run:  ls

          - name: Get repository code
            #run: echo test ci cd
            uses: actions/checkout@v4
          
          - name: npm installation
            #-name: npm ci
            run: npm ci
          
          - name: Test app
            run: npm run test
    lint:
      runs-on: ubuntu-latest
      steps:
          - name: Get repository code
            #run: echo test ci cd
            uses: actions/checkout@v4
          
          - name: npm installation
            #-name: npm ci
            run: npm ci

          - name: lint installation
            #-name: npm ci
            run: npm install --save-dev eslint-config-react-app eslint
          
          - name: lint app
            run: npm run lint
    buils:
       runs-on: ubuntu-latest
       steps:
          - name: Get repository code
          #run: echo test ci cd
            uses: actions/checkout@v4
        
          - name: npm installation
            #-name: npm ci
            run: npm ci
          
          - name: Build
            run: npm run build

          - name: Deploy..
            run: echo Deploy