name: Upload - Download
on:
  push:
    #branches:
    #  - master
    #  - main
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run build

      - name: upload folder
        uses: actions/upload-artifact@v3
        with:
          path: uploaddemo
          key: uploaddemo

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v3
        with:
          name: uploaddemo
